import { createId, readFileAsDataUrl } from "./cms";
export function bindModalSave(modal, setModal, update){
  if(!modal) return null;
  const item=modal.item;
  const field=(name,label,type="text")=><label>{label}{type==="textarea"?<textarea rows="6" value={item[name]||""} onChange={e=>setModal({...modal,item:{...item,[name]:e.target.value}})}/>:<input type={type} value={item[name]||""} onChange={e=>setModal({...modal,item:{...item,[name]:e.target.value}})}/>}</label>;
  const upload=async name=>{const input=document.createElement("input");input.type="file";input.accept="image/*";input.onchange=async()=>{if(input.files?.[0])setModal({...modal,item:{...item,[name]:await readFileAsDataUrl(input.files[0])}})};input.click()};
  const save=(target,collection)=>{const value={...item,id:item.id||createId(target)};if(target==="folder"&&!Array.isArray(value.photos))value.photos=[];update(d=>{const arr=collection(d);if(item.id){const i=arr.findIndex(x=>x.id===item.id);arr[i]=value}else{value.order=arr.length+1;arr.push(value)}});setModal(null)};
  let body=null,onSave=null;
  if(modal.type==="testimonial"||modal.type==="employee"){body=<div className="adm-form">{field("name","Name")}{field(modal.type==="employee"?"designation":"role",modal.type==="employee"?"Designation":"Role")}{field("text","Testimonial","textarea")}<button className="adm-secondary" onClick={()=>upload("image")}>Upload Photo</button>{item.image&&<img className="adm-preview" src={item.image} alt=""/>}<label>Publish<select value={item.published===false?"no":"yes"} onChange={e=>setModal({...modal,item:{...item,published:e.target.value==="yes"}})}><option value="yes">Published</option><option value="no">Draft</option></select></label></div>;onSave=()=>save("testimonial",d=>modal.scope==="home"?d.homepage.clientTestimonials:d.career.employeeTestimonials)}
  else if(modal.type==="blog"){body=<div className="adm-form">{field("title","Title")}{field("content","Content","textarea")}<button className="adm-secondary" onClick={()=>upload("image")}>Upload Featured Image</button>{item.image&&<img className="adm-preview" src={item.image} alt=""/>}</div>;onSave=()=>save("blog",d=>d.homepage.blogs)}
  else if(modal.type==="team"){body=<div className="adm-form">{field("name","Name")}{field("designation","Designation")}{field("linkedin","LinkedIn URL","url")}<button className="adm-secondary" onClick={()=>upload("photo")}>Upload Photo</button>{item.photo&&<img className="adm-preview" src={item.photo} alt=""/>}</div>;onSave=()=>save("team",d=>d.company.team)}
  else if(modal.type==="job"){body=<div className="adm-form">{field("title","Job Title")}{field("department","Department")}{field("location","Location")}{field("experience","Experience")}{field("type","Job Type")}{field("description","Description","textarea")}{field("responsibilities","Responsibilities","textarea")}{field("requirements","Requirements","textarea")}{field("applicationEmail","Application Email","email")}<label>Publish<select value={item.published?"yes":"no"} onChange={e=>setModal({...modal,item:{...item,published:e.target.value==="yes"}})}><option value="no">Draft</option><option value="yes">Published</option></select></label></div>;onSave=()=>save("job",d=>d.career.jobs)}
  else if(modal.type==="folder"){body=<div className="adm-form">{field("title","Folder Name")}</div>;onSave=()=>save("folder",d=>d.gallery.folders)}
  return {body,onSave};
}
